app:
  ui: true

robot:
 moli:
  api: http://i.itpk.cn/api.php
  key:
  secret:
 tuling:
  api: http://www.tuling123.com/openapi/api
  key:
  secret:
 simsimi:
  api: "https://secureapp.simsimi.com/v1/simsimi/talkset?ak=no_auth&av=6.8.9.0&cc=CN&isFilter=0&lc=ch&message_sentence=%s&normalProb=10&os=i&tz=Asia/Shanghai&uid=199106325"

wx:
  imgpath: tmp
  qrimg: temp.jpg
  data: data